### ISSUE TITLE
Request fulfillment gas price research

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-governance#1]
Airnode fulfills requests by making a transaction, and this requires a gas price to be set. A gas price too low causes too much delay, a gas price too high is wasteful. We need a statistically-sound method to set this value optimally.

## Deliverables

- There is [research](https://hal.inria.fr/hal-02403098/document) concluding that future gas prices can't be estimated based on past gas prices. Therefore, feasibility of such a method is moot, and should be investigated.

- Assuming such a method is feasible, we need one for the request-response protocol, and one for the publish-subscribe protocol. See below for details.

## Constraints

There are two ways of getting historical gas prices through Ethereum calls

1. Use [eth_gasprice](https://eth.wiki/json-rpc/API#eth_gasprice) to get the gas price recommended by the Ethereum node.
For geth, this is achieved by sampling transactions from the last `checkBlocks`, sorting them and getting the `percentile`-th gas price. See the [code](https://github.com/ethereum/go-ethereum/blob/6b9858085f8e10d50df3bf09d0a5dfd59b683d05/eth/gasprice/gasprice.go#L97) and the [default values](https://github.com/ethereum/go-ethereum/blob/328901c24cdcbfe57ad983248b2fd481f495db3d/eth/config.go#L37) (`20` and `60%`).

1. Fetch last N blocks, sample individual transactions from them and make the calculation above yourself.

In our case, (2) is not viable because it makes too many calls. Therefore, the proposed method has to use the gas price suggested by the node. Here, we are will assume that the Ethereum node is using the default parameters.

Here, a workable alternative is sampling a very limited number of transactions (`3-7`) from the most recent block. This would work especially well if it is actually impossible to infer future gas prices from previous ones, because then, the data collected from the last `20` blocks would act as noise and it would be preferable to omit them completely.

## Request-response protocol

The request-response protocol is special in that we have an additional point of data, the number of blocks that have been confirmed since the request has been made (let's call it `block_delta`). Although Airnode is stateless/memoryless, when it detects an incoming request, it can check its block number and the current block number to calculate `block_delta`, which represents how late Airnode is to fulfill that request. Therefore, this can be used as a parameter in the model. For example:

```
eth_gasprice * (1.2 + block_delta / 10)
```
which means that each time Airnode attempts to fulfill this request, it will use a larger gas price because `block_delta` will be increasing with time.

## Publish-subscribe protocol

In the publish-subscribe protocol, Airnode gets triggered to fulfill the request through an off-chain source, which means that it will not know if it has attempted to fulfill this request before. In short, there is no `block_delta`, and the model can only use the gas price recommended by the node, such as:
```
eth_gasprice * 1.2
```

It's also possible that `block_delta` is not a very useful parameter, and both request-response and publish-subscribe use the same simple model where the recommended gas price is multiplied by a constant.

## Data

The temporal resolution of the problem at hand is at the level of blocks, and thus the data used have to be as fine-grained as possible. This means that you would need to fetch the gas prices of all transactions between a block range. However, since the time-scale is short (i.e, the transaction going through in >10 blocks is not acceptable), a representative block range does not have to be too large. This means that one can sample 1000 consecutive blocks at different network conditions and run the analysis on these samples.

## Metrics

It would be ideal to assess the proposed method by probabilistic metrics, e.g., if you use `eth_gasprice * 1.2`, the transaction will go through in less than `3` blocks with `80%` certainty. Overall, we are more interested in the upper bounds (rather than averages or lower bounds), i.e., we don't want the transaction to be delayed more than `N` blocks.

## Stationarity

The proposed method should be tested in various network conditions for stationarity. For example, if the proposed model is
```
eth_gasprice * k
```
we would need to know if `k` drifts over time. It would be ideal to find a model that the network is stationary for, but in the absence of such a model, one where drift is very slow is also acceptable.

## EIP-1559

This research will likely have to be repeated after [EIP-1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md) is implemented. It would be ideal if the report could comment on what effect EIP-1559 would have on the proposed method to determine the gas price.

**Comment by sassmilic** [comment]
> In our case, (2) is not viable because it makes too many calls.

Too many calls in terms of what: Cost of calls? Length of time for final response?

**Comment by sassmilic** [comment]
>There is research concluding that future gas prices can't be estimated based on past gas prices. Therefore, feasibility of such a method is moot, and should be investigated.

Can you show me where in the paper they say this? It seems like they only used gas prices as the observable variable.

**Comment by bbenligiray** [comment]
> Too many calls in terms of what: Cost of calls? Length of time for final response?

Both. It's burdensome on the node/costly in terms of using up call limits, and takes too long of Airnode's time.

> Can you show me where in the paper they say this?

Last page, full paragraph:

> In light of the results of the pair-wise Granger causality test (see Table V), a non-directional causality relationship was observed between the data series on the `oracle_gasprice` variable and the data series on the `block_time` variable and between the data series on the `oracle_gasprice` variable and the data series on the `hashrate` variable. This means that the past history of both the `oracle_gasprice` and the `blocktime` variables cannot help in respectively predicting their future values.

**Comment by sassmilic** [comment]
I feel kinda iffy on their conclusion because that would imply all ETH gas station's are useless. I think it would depend on the granularity of their lookback window, although I'm not familiar with "Granger causality" which they use to get their results.

**Comment by bbenligiray** [comment]
> that would imply all ETH gas station's are useless

Yes. At least at the block scale. But for example there is definitely daily seasonality.

Granularity is at the block-level so it fits our problem.

Their conclusion can be justified through the random walk hypothesis; which implies that the gas price market is efficient. As soon as you develop a way to estimate gas prices and open that to the public, it becomes useless, very similar to what would happen to a successful trading algorithm.

**Comment by sassmilic** [comment]
>which implies that the gas price market is efficient

I don't this applies as much here where most transactions use the built-in gas prices their wallet suggests. You also don't have arbitrageurs that keep most other markets "efficient".

But it doesn't make sense to argue about this until we actually look at the data.

**Comment by bbenligiray** [comment]
This was concluded a while ago
